version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Kuala_Lumpur"
    open-pull-requests-limit: 10
    groups:
      go-dependencies:
        patterns:
          - "*"
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Kuala_Lumpur"
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Kuala_Lumpur"
    open-pull-requests-limit: 10
    groups:
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Kuala_Lumpur"
    open-pull-requests-limit: 10
    groups:
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
